name: Build

on:
  push:
    branches:
      - web
  pull_request:
    branches:
      - web

jobs:
  deploy:
    runs-on: windows-latest
    if: (github.event_name == 'push')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install DocFX
        run: choco install docfx -y

      - name: Build
        run: docfx docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
