name: Build

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - web
  pull_request:
    branches:
      - web

jobs:
  deploy:
    runs-on: windows-latest
    if: (github.event_name == 'push')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Update EXT directory
        run: |
          git submodule update --remote
          
      - name: Commit EXT directory
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub logo
          committer_name: GitHub Actions
          committer_email: github-actions[bot]@users.noreply.github.com
          add: ext/**

      - name: DocFX
        run: |
          choco install docfx -y
          docfx docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
